### ISSUE TITLE
Need access to Cloud Feeds build

### ISSUE THREAD

**Issue by meker12** [deconst/strider-deconst-control#19]
```Not authorized for configuring this project```  @smashwilson  Can you help?

**Comment by smashwilson** [comment]
We discussed this offline, but configuration access is intentionally kind of locked down because [content repository builds should be treated as generated content, now](https://github.com/rackerlabs/docs-migration/issues/104#issuecomment-191536136). As it turns out there's actually very little to configure, anyway! Just the API keys and content service URLs (staging and production) which would, uh, break everything if you changed them.

I tried to make the builder generic enough to (when possible, automatically) do all of the things that we needed to do with the content builds on Travis or ci.deconst.horse. If you need to change what they do, file me an issue on [strider-deconst-content](https://github.com/deconst/strider-deconst-content) and then _all_ of the builds will get that capability at once.
